apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mt5-trading-system
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containers:
      - image: gcr.io/grand-ability-469012-p4/mt5-trading-system
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"